#!/bin/bash

USERFILES="--mount type=bind,source=/etc/passwd,target=/etc/passwd,readonly --mount type=bind,source=/etc/group,target=/etc/group,readonly"
USERVOLS="--volume /etc/passwd:/etc/passwd:ro --volume /etc/group:/etc/group:ro"
USERX="--user $(id -u):$(id -g) "
if [ $(id -u) = 0 ]; then
	HDIR='/root/'
else
	HDIR="/home/$(id -nu)/"
fi

if [ -f ${HDIR}/.my.cnf ]; then
	CNF="--mount type=bind,source=${HDIR}.my.cnf,target=/root/.my.cnf,readonly --mount type=bind,source=${HDIR}.my.cnf,target=${HDIR}.my.cnf,readonly"
    CBFVOL="--volume ${HDIR}.my.cnf:/root/.my.cnf:ro --volume ${HDIR}.my.cnf:${HDIR}.my.cnf:ro"
	#echo ${CNF}
fi

if [ -L "${0}" ]; then
  # Symbolic link. Get the actual file location
  ROOT=$(readlink ${0})
else
  ROOT=${0}
fi
echo
PROJDIR="$(dirname ${ROOT})"

#docker run -it --rm ${USERFILES} ${CNF} ${USERX}  kd2qar/callinfo /callinfo/callquery.py ${@} 
docker compose --project-directory ${PROJDIR} run --quiet-pull -i --rm --remove-orphans ${USERVOLS} ${CNFVOL} ${USERX} callinfo /callinfo/callquery.py ${@}
